=== archway-network/contract-register/schemas/metadata.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/CodeMetadata",
  "definitions": {
      "CodeMetadata": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "code_id": {
                  "type": "integer"
              },
              "source": {
                  "$ref": "#/definitions/Source"
              },
              "source_builder": {
                  "$ref": "#/definitions/SourceBuilder"
              },
              "schema": {
                  "type": "string"
              },
              "contacts": {
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
              }
          },
          "required": [
              "code_id",
              "schema"
          ],
          "title": "CodeMetadata"
      },
      "Source": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "repository": {
                  "type": "string",
                  "format": "uri",
                  "qt-uri-protocols": [
                      "https"
                  ]
              },
              "tag": {
                  "type": "string"
              },
              "license": {
                  "type": "string"
              }
          },
          "required": [
              "repository",
              "tag"
          ],
          "title": "Source"
      },
      "SourceBuilder": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "image": {
                  "type": "string"
              },
              "tag": {
                  "type": "string"
              },
              "contract_name": {
                  "type": "string"
              }
          },
          "required": [
              "contract_name",
              "image",
              "tag"
          ],
          "title": "SourceBuilder"
      }
  }
}

=== archway-network/contract-register/mainnet/4/metadata.json
{
    "code_id": 4,
    "source": {
        "repository": "https://github.com/DA0-DA0/dao-contracts",
        "tag": "v2.1.0",
        "license": "BSD 3-Clause"
    },
    "source_builder": {
        "image": "cosmwasm/workspace-optimizer",
        "tag": "0.12.11",
        "contract_name": "dao_proposal_single.wasm"
    },
    "schema": "schema.json",
    "contacts": []
}

=== archway-network/contract-register/mainnet/110/metadata.json
{
    "code_id": 110,
    "source": {
        "repository": "https://github.com/noislabs/nois-contracts",
        "tag": "",
        "license": "Apache License 2.0"
    },
    "source_builder": {
        "image": "cosmwasm/workspace-optimizer",
        "tag": "",
        "contract_name": "nois_proxy.wasm"
    },
    "schema": "",
    "contacts": []
}
